---
- hosts: 
    - zookeepers
    - kafkas
  gather_facts: false
  become: true

  tasks:

    - name: "Install Docker"
      apt:
              pkg:
                      - docker.io 
                      - docker-compose
              state: present
              update-cache: yes

    - name: "Install pip"
      apt:
              pkg:
                      - python3-pip
              state: present
              update-cache: yes
    - name: "Install docker python modules"
      pip:
              name:
                      - docker
                      - docker-compose
