---
- hosts: monitor
  gather_facts: false
  become: true

  tasks:

    - name: "Install Prometheus"
      apt:
              pkg:
                      - prometheus
              state: present
              update-cache: yes

    - name: "Configure Prometheus"
      copy:
        src: prometheus/prometheus.yml
        dest: /etc/prometheus/prometheus.yml

- hosts: zookeepers:kafkas:mirrors
  gather_facts: false
  become: true

  tasks:

    - name: "Install Prometheus node exporter"
      apt:
              pkg:
                      - prometheus-node-exporter
              state: present
              update-cache: yes

    - name: "Create JMX exporter directories"
      file:
        path: /opt/jmx_exporter
        state: directory

    - name: "Get JMX exporter jar"
      get_url:
        url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.0/jmx_prometheus_javaagent-0.3.0.jar
        dest: /opt/jmx_exporter/jmx_prometheus_javaagent.jar
        mode: '0644'

    - name: "JMX exporter config files"
      copy:
        src: "prometheus/{{ item }}.yml"
        dest: "/opt/jmx_exporter/{{ item }}.yml"
      with_items:
        - zookeeper
        - kafka
        - mirrormaker

