---
- hosts: kafkas
  gather_facts: false
  become: true

  vars:
     domain: "epicyclist.uk"
     num_partitions: "{{ 16 }}"
     retention_ms: "{{ 7 * 24 * 60 * 60 * 1000 }}"
     retention_bytes: "{{ -1 }}"

  tasks:
    - name: "Create data fs"
      filesystem:
        fstype: xfs
        dev: /dev/vdb
    - name: "Mount data fs"
      mount:
        path: /kafka
        src: /dev/vdb
        fstype: xfs
        state: mounted
    - name: "Create data dir"
      file:
        path: /kafka/data
        state: directory
    - name: "Deploy our Kafka compose file"
      template:
        src:  kafka/kafka-compose.yaml.j2
        dest: kafka-compose.yml
      vars:
        mntpath: '/kafka/data'
        logpath: '/kafka/data'

    - name: "Start our Kafka services"
      docker_service:
        project_src:
            '.'
        files:
          - kafka-compose.yml
        services:
          - kafka
        state:
          present
