---
- hosts: kafkas
  gather_facts: false
  become: true

  vars:
     domain: "epicyclist.uk"
     num_partitions: "{{ 16 }}"
     retention_ms: "{{ 7 * 24 * 60 * 60 * 1000 }}"
     retention_bytes: "{{ -1 }}"
     data_fs:
       - { dev: "/dev/vdb", path: "/kafka/data" }
       - { dev: "/dev/vdc", path: "/kafka/data2" }



  tasks:
    - name: "Create data filesystems"
      filesystem:
        fstype: xfs
        dev: "{{ item.dev }}"
      with_items: "{{ data_fs }}"
    - name: "Create data mountpoints"
      file:
        path: "{{ item.path }}"
        state: directory
      with_items: "{{ data_fs }}"
    - name: "Mount data filesystems"
      mount:
        path: "{{ item.path }}"
        src: "{{ item.dev }}"
        fstype: xfs
        opts: nofail
        state: mounted
      with_items: "{{ data_fs }}"
    - name: "Deploy our Kafka compose file"
      template:
        src:  kafka/kafka-compose.yaml.j2
        dest: kafka-compose.yml
      vars:
        mntpath: '/kafka/data'
        logpath: '/kafka/data'
        mntpath2: '/kafka/data2'
        logpath2: '/kafka/data2'

    - name: "JAAS config file"
      copy:
        src: "kafka/kafka_server_jaas.conf"
        dest: "/etc/kafka_server_jaas.conf"


    - name: "Start our Kafka services"
      docker_service:
        project_src:
            '.'
        files:
          - kafka-compose.yml
        services:
          - kafka
        state:
          present
