---
- hosts: mirrors
  gather_facts: true
  become: true

  vars:
    numstreams: 7
    source: "public.alerts.ztf.uw.edu:9092"
    group_id: "dev3.ztf-mirror.roe.ac.uk"
    target: "{{ groups['kafkas'] | join(':29092,') }}:29092"
#   topicdate:  "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
#   topiclist: [
#       "ztf_{{ topicdate }}_programid1",
#       "ztf_{{ topicdate }}_programid3_public"
#       ]
    topiclist: [
        "topicname"
        ]

  tasks:

    - name: "Create /etc/mirror directory"
      file:
        path: /etc/mirror
        state: directory

    - name: "Deploy our MirrorMaker producer config"
      template:
        src:  mirror/producer.config.j2
        dest: /etc/mirror/producer.config

    - name: "Deploy our MirrorMaker consumer config"
      template:
        src:  mirror/consumer.config.j2
        dest: /etc/mirror/consumer.config

    - name: "Deploy our MirrorMaker compose file"
      template:
        src:  mirror/mirror-compose.yml.j2
        dest: mirror-compose.yml

    - name: "Start our MirrorMaker services"
      docker_service:
        project_name: mirrormaker
        project_src:
            '.'
        files:
          - 'mirror-compose.yml'
        services:
          - 'mirrormaker'
        state:
          present
