---
- hosts: mirrors
  gather_facts: true

  tasks:

  - name: "Check the cron daemon is installed"
    become: true
    apt:
      name:  cron
      state: present

  - name: "Check the cron daemon is enabled and started"
    become: true
    service:
      enabled: true
      name:  cron
      state: started

  - name: "Create the user's bin directory"
    file:
      path: 'bin'
      state: directory

  - name: "Deploy our topic update script"
    copy:
      src:  'mirror/bin/update-topic.sh'
      dest: 'bin/update-topic.sh'
      mode: 'u=rx,g=,o='

# Needs to run after midnight UTC and before start of observations
  - name: "Install our crontab entry"
    cron:
      name:   "Update topics"
      user:   "{{ansible_env.USER}}"
      minute: '28'
      hour:   '0'
      job:    "{{ansible_env.HOME}}/bin/update-topic.sh"
