---
- hosts: monitor
  gather_facts: false
  become: true

  tasks:

    - name: "Add Grafana repo"
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: "Add Grafana GPG key"
      apt_key:
        id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: "Install Grafana"
      apt:
        pkg:
          - grafana
        state: present
        update-cache: yes

    - name: "Enable Grafana service"
      service:
        enabled: true
        name:  grafana-server
        state: started

    - name: "Set admin password"
      script: grafana/set-admin-pw.sh
      args:
        creates: /root/grafana.admin.password.txt
      register: output

    - debug: var=output.stdout_lines


