all:
        children:
                zookeepers:
                        hosts:
                                zookeeper0:
                                zookeeper1:
                        vars:
                                ansible_python_interpreter: /usr/bin/python3

