all:
        vars:
                ansible_python_interpreter: /usr/bin/python3
        children:
                zookeepers:
                        hosts:
                                mirror-1:
                                mirror-2:
                mirrors:
                        hosts:
                                mirror-1:
                                mirror-2:
                kafkas:
                        hosts:
                                kafka-1:
                                kafka-2:
