
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    #scrape_interval: 5s
    #scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: admin-node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: ['localhost:9100']

  - job_name: mirror-nodes
    static_configs:
      - targets: 
        - 'mirror-1:9100'
        - 'mirror-2:9100'

  - job_name: kafka-nodes
    static_configs:
      - targets: 
        - 'kafka-1:9100'
        - 'kafka-2:9100'
        - 'kafka-3:9100'

  - job_name: 'zookeepers'
    static_configs:
      - targets: 
        - 'mirror-1:8082'
        - 'mirror-2:8082'

  - job_name: 'mirrormakers'
    static_configs:
      - targets: 
        - 'mirror-1:8081'
        - 'mirror-2:8081'

  - job_name: 'kafkas'
    static_configs:
      - targets: 
        - 'kafka-1:8080'
        - 'kafka-2:8080'
        - 'kafka-3:8080'

    metric_relabel_configs:
      # Relabel: topic=ztf_20180425_programid2 -> night=20180425, program=MSIP
      - source_labels: [ topic ]
        regex: "ztf_(\\d+)_.*"
        target_label: "night"
        replacement: "$1"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid0"
        target_label: "program"
        replacement: "Commissioning"
      - source_labels: [ topic ]
        regex: "ztf_\\d+_programid1"
        target_label: "program"
        replacement: "MSIP"
